# GRPO Algorithm Configuration
grpo:
  num_prompts_per_step: 128
  num_generations_per_prompt: 32
  max_num_steps: 1000000
  normalize_rewards: true
  use_leave_one_out_baseline: false
  val_period: 5
  val_at_start: false
  max_val_samples: 128
  val_batch_size: 128

loss_fn:
  reference_policy_kl_penalty: 0
  ratio_eps_min: 0.2
  ratio_eps_max: 0.2

checkpointing:
  enabled: true
  checkpoint_dir: "results/grpo_v2"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 10
  save_period: 5

policy:
  model_name: "Qwen/Qwen2.5-7B"
  tokenizer_name: ${policy.model_name}
  train_global_batch_size: 4096
  train_micro_batch_size: 1
  generation_batch_size: 32 # Only used when generating using HF backend
  logprob_batch_size: 2
  max_total_sequence_length: 5888
  precision: "bfloat16"

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 1e-6
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 5
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [5]

  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    vllm_cfg:
      tensor_parallel_size: 2
      gpu_memory_utilization: 0.7
      max_model_len: ${policy.max_total_sequence_length}

data:
  max_input_seq_length: 1024 # upper bound, real truncation occurs at vllm.max_model_len
  prompt_file: "examples/r1/cot.txt"
  system_prompt_file: null
  dataset_name: "math-cl"

env:
  math:
    num_workers: 8

logger:
  log_dir: "logs"  # Base directory for all logs
  num_val_samples_to_print: 2 # Number of validation samples to pretty print on terminal
  wandb_enabled: true
  tensorboard_enabled: false
  monitor_gpus: false  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  wandb:
    project: "reinforcer_grpo_qwen2_5_7b_cl"
    name: "eos-qwen2_5_7b_grpo_cl_v2"
  tensorboard: {}
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 8
  num_nodes: 1
