# Evaluation Configuration
generation:
  backend: "vllm" # only vllm is supported for evaluation
  max_new_tokens: ${generation.vllm_cfg.max_model_len}
  temperature: 0.6
  top_p: 0.95
  top_k: 20 # disable
  num_prompts_per_step: 4 # -1 means pass all prompts at once
  model_name: "Qwen/Qwen2.5-1.5B-Instruct"
  stop_token_ids: null
  stop_strings: null
  vllm_cfg:
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.9
    max_model_len: 16384

tokenizer:
  name: ${generation.model_name} ## specify if you'd like to use a tokenizer different from the model's default
  chat_template: "default"

data:
  max_input_seq_length: ${generation.vllm_cfg.max_model_len} # useless since we directly use prompts in evaluation
  prompt_file: "examples/prompts/gpqa.txt"
  system_prompt_file: null
  dataset_name: "Idavidrein/gpqa"
  dataset_subset: "gpqa_diamond"
  dataset_split: "train"

env:
  math:
    num_workers: 8
    extraction_config: null # use default extraction config

cluster:
  gpus_per_node: 1
  num_nodes: 1
