# GRPO Algorithm Configuration for GenRM RLHF
grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 8
  num_val_generations_per_prompt: 4  # Number of responses to generate per prompt during validation
  max_rollout_turns: 1 # Single turn evaluation task
  max_num_epochs: 1
  max_num_steps: 1000000
  normalize_rewards: true
  use_leave_one_out_baseline: true
  val_period: 10
  val_at_start: false
  overlong_filtering: false
  max_val_samples: 32
  val_batch_size: 32
  seed: 42
  async_grpo:
    enabled: false # Set to true to enable async training mode
    # Max age (in training steps) for trajectories used in training
    max_trajectory_age_steps: 1

loss_fn:
  reference_policy_kl_penalty: 0.01
  ratio_clip_min: 0.2
  ratio_clip_max: 0.2
  ratio_clip_c: null
  # (default off) loss formulation improvements (docs/guides/grpo.md#loss)
  use_on_policy_kl_approximation: false
  # Async GRPO requires importance sampling correction enabled
  # Set to true when async_grpo.enabled is true
  use_importance_sampling_correction: false
  sequence_level_importance_ratios: false
  token_level_loss: true
  imp_clip_max: null  # Maximum value for importance sampling weight clipping (null to disable)

checkpointing:
  enabled: true
  checkpoint_dir: "results/grpo_genrm_rlhf"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 3
  save_period: 10
  checkpoint_must_save_by: null
  model_save_format: "safetensors"
  save_consolidated: false

policy:
  model_name: "Qwen/Qwen2.5-1.5B"  # Use base model, not instruct version
  tokenizer:
    name: ${policy.model_name} ## specify if you'd like to use a tokenizer different from the model's default
  train_global_batch_size: 512
  train_micro_batch_size: 4
  generation_batch_size: 32 # Only used when generating using HF backend
  logprob_batch_size: 4
  max_total_sequence_length: 8192  # Increased for long evaluation prompts
  precision: "bfloat16"
  logprob_chunk_size: null

  dtensor_cfg:
    _v2: true
    enabled: true
    cpu_offload: False
    sequence_parallel: false
    activation_checkpointing: false
    tensor_parallel_size: 1
    context_parallel_size: 1
    custom_parallel_plan: null
  
  megatron_cfg:
    enabled: false
    empty_unused_memory_level: 0
    activation_checkpointing: false
    converter_type: "Qwen2ForCausalLM"
    tensor_model_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    sequence_parallel: false
    freeze_moe_router: true
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none" # "seq_aux_loss" causes logprob error divergence for grpo
    moe_router_bias_update_rate: 0.0 # by default, disable bias updates for grpo
    moe_permute_fusion: false
    #gives ~20% training perf speedup with sequence packing
    apply_rope_fusion: True
    defer_fp32_logits: null

    optimizer:
      optimizer: "adam"
      lr: 5.0e-6
      min_lr: 5.0e-7
      weight_decay: 0.01
      bf16: true
      fp16: false
      params_dtype: "float32"

      #adam
      adam_beta1: 0.9
      adam_beta2: 0.999
      adam_eps: 1e-8

      #sgd
      sgd_momentum: 0.9

      #distributed optimizer
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true

      clip_grad: ${policy.max_grad_norm}

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "constant"
      lr_decay_iters: 1000
      lr_warmup_iters: 13
      lr_warmup_init: 5.0e-7

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      use_custom_fsdp: false
      data_parallel_sharding_strategy: "optim_grads_params"

    env_vars: null

  # See docs/design-docs/sequence-packing-and-dynamic-batching.md 
  # for more details on dynamic batching and sequence packing.
  dynamic_batching:
    enabled: False
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.logprob_batch_size}}
    sequence_length_round: 64

  sequence_packing:
    enabled: True
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.logprob_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64

  # makes the training sequence length divisible by the tensor parallel size
  # this is useful for sequence parallel training
  make_sequence_length_divisible_by: ${policy.dtensor_cfg.tensor_parallel_size}
  max_grad_norm: 1.0

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 5.0e-6
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8
      # when using Dtensor, we need to set foreach
      # and fused to False
      foreach: False
      fused: False

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 50
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [50]

  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    stop_token_ids: null
    stop_strings: null
    vllm_cfg:
      async_engine: false
      precision: ${policy.precision}
      tensor_parallel_size: 1
      pipeline_parallel_size: 1
      enable_expert_parallel: false
      gpu_memory_utilization: 0.6
      max_model_len: ${policy.max_total_sequence_length}
      enforce_eager: False
      use_deep_gemm: False
      num_last_layers_in_bf16: 0
      num_first_layers_in_bf16: 0
    vllm_kwargs:
      compilation_config:
        # when enforce_eager is False, set ++policy.generation.vllm_kwargs.compilation_config.use_inductor=False for better accuracy,
        # with the flag, vllm will use the custom CUDA kernels instead of the Triton kernels generated by torch.compile
        # for more details, see convergence issue https://github.com/NVIDIA-NeMo/RL/issues/998
        use_inductor: False
    colocated:
      # true: generation shares training GPUs
      # false: uses dedicated generation resources
      enabled: true
      # only relevant when enabled is false
      resources:
        gpus_per_node: null # Decides num gpus to be dedicated to generation when there is one node in the cluster i.e cluster.num_nodes == 1
        num_nodes: null # Decides number of nodes to be dedicated to generation

# Data configuration
data:
  max_input_seq_length: ${policy.max_total_sequence_length} # upper bound, real truncation occurs at vllm.max_model_len
  prompt_file: null  # Optional prompt template file
  system_prompt_file: null  # Optional system prompt file
  shuffle: true
  dataset_name: "genrm_rlhf"
  train_data_path: "path/to/your/train.jsonl"  # Update with your data path
  val_data_path: "path/to/your/val.jsonl"      # Optional validation data path

env:
  genrm_rlhf:
    num_workers: 2 # Number of parallel GenRM workers
    model_name: "nvidia/Llama-3_3-Nemotron-Super-49B-GenRM" # GenRM model for pairwise comparison
    tensor_parallel_size: 4 # TP size for the GenRM model (requires substantial GPU memory)
    gpu_memory_utilization: 0.95 # GPU memory utilization for GenRM model
    max_model_len: 40000 # Max sequence length for GenRM model
    num_generations_per_prompt: ${grpo.num_generations_per_prompt} # The expected number of responses to generate per prompt during training
    num_val_generations_per_prompt: ${grpo.num_val_generations_per_prompt} # The expected number of responses per prompt during validation
    num_judges_per_comparison: 1 # Number of independent GenRM passes per pairwise comparison (for majority voting)
    temperature: 0.0 # GenRM temperature (usually 0 for deterministic evaluation)
    top_p: 1.0 # Optional sampling parameter for vLLM
    max_tokens: 32768 # Max tokens for GenRM's comparison output
    stop: null # Stop strings for GenRM evaluation
    reasoning_split_word: "</think>" # The word to split the response into reasoning and answer
    max_concurrency: 16 # Maximum concurrent step calls for the environment actor
    # Reward aggregation configuration
    aggregator_method: "simple_tiebreaker" # Options: "weighted_win_loss", "simple_tiebreaker", "individual_scores"
    # aggregator_config: # Additional config for the aggregator
    #   score_mapping: # Mapping from ranking scores (1-6) to weighted points for weighted_win_loss
    #     1: 1.0    # Much better
    #     2: 0.8   # Better
    #     3: 0.6    # Slightly better
    #     4: 0.4    # Slightly worse
    #     5: 0.2   # Worse
    #     6: 0.0    # Much worse

# Logger configuration
logger:
  log_dir: "logs"  # Base directory for all logs
  num_val_samples_to_print: 0 # Number of validation samples to pretty print on terminal
  wandb_enabled: false
  tensorboard_enabled: false
  mlflow_enabled: false  # Disable MLflow logging
  monitor_gpus: true  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  wandb:
    project: "grpo-genrm-rlhf"
    name: "grpo-genrm-rlhf-logger"
  tensorboard: {}
  mlflow:
    experiment_name: "grpo-genrm-rlhf"
    run_name: "grpo-genrm-rlhf-logger"
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 1
  num_nodes: 1