grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 8
  max_rollout_turns: 10  # for multi-turn rollouts with tools
  max_num_steps: 1000
  normalize_rewards: true
  use_leave_one_out_baseline: true
  val_period: 50
  val_at_start: false
  max_val_samples: 64
  val_batch_size: 32

loss_fn:
  reference_policy_kl_penalty: 0.001
  ratio_clip_min: 0.2
  ratio_clip_max: 0.28
  ratio_clip_c: null
  use_on_policy_kl_approximation: false
  use_importance_sampling_correction: false
  token_level_loss: true

checkpointing:
  enabled: true
  checkpoint_dir: "checkpoints/grpo_math_tools"
  metric_name: "val_reward"
  higher_is_better: true
  keep_top_k: 3
  save_period: 100

policy:
  model_name: "Qwen/Qwen3-8B"
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 64
  train_micro_batch_size: 2
  generation_batch_size: 16
  logprob_batch_size: 2
  max_total_sequence_length: 8192
  precision: "bfloat16"
  fsdp_offload_enabled: false
  activation_checkpointing_enabled: false
  refit_buffer_size_gb: 4

  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: false
    activation_checkpointing: true
    tensor_parallel_size: 1
    custom_parallel_plan: null

  dynamic_batching:
    enabled: true
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.logprob_batch_size}}
    sequence_length_round: 64

  make_sequence_length_divisible_by: ${policy.dtensor_cfg.tensor_parallel_size}
  max_grad_norm: 1.0

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 2.0e-6
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8
      foreach: false
      fused: false

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 50
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [50]

  generation:
    backend: "vllm"
    max_new_tokens: 8192
    temperature: 1.0
    top_p: 1.0
    top_k: 20
    stop_token_ids: null
    stop_strings: ["</tool_call>", "<|im_end|>", "✿RESULT✿:", "✿RETURN✿:"] # qwen
    vllm_cfg:
      precision: ${policy.precision}
      tensor_parallel_size: 1
      gpu_memory_utilization: 0.7
      max_model_len: ${policy.max_total_sequence_length}

data:
  dataset_name: "DeepScaler"
  max_input_seq_length: ${policy.max_total_sequence_length}
  prompt_file: "examples/prompts/math_tools_prompt.txt"
  system_prompt_file: "examples/prompts/math_tools_system.txt"

env:
  math_tools:
    max_turns: 20
    max_bash_timeout: 30
    max_file_size: 1048576  # 1MB
    enable_network: false
    memory_limit: 512
    cpu_limit: 1.0

logger:
  log_dir: "logs/grpo_math_tools"
  num_val_samples_to_print: 0
  wandb_enabled: false
  tensorboard_enabled: false
  monitor_gpus: false
  wandb:
    project: "math-tools-rl"
    name: "grpo-math-tools"
  tensorboard: {}
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 4 

