sft:
  max_num_epochs: 1
  max_num_steps: 250
  val_period: 10
  val_batches: 8
  val_global_batch_size: 64
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: results/sft-dsv3-megatron
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 10
policy:
  model_name: /lustre/fsw/portfolios/coreai/users/yifuw/hf_checkpoints/dsv3/DeepSeek-V3-BF16
  tokenizer:
    name: /lustre/fsw/portfolios/coreai/users/yifuw/hf_checkpoints/dsv3/DeepSeek-V3-BF16
  train_global_batch_size: 128
  train_micro_batch_size: 1
  max_total_sequence_length: 1024
  precision: bfloat16
  fsdp_offload_enabled: false
  activation_checkpointing_enabled: false
  dtensor_cfg:
    enabled: false
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  max_grad_norm: 1
  optimizer: null
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 0
    activation_checkpointing: false
    tensor_model_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 64
    pipeline_model_parallel_size: 8
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    num_layers_in_first_pipeline_stage: 7
    num_layers_in_last_pipeline_stage: 6
    sequence_parallel: false
    freeze_moe_router: false
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none" # "seq_aux_loss" causes logprob error divergence for grpo
    moe_router_bias_update_rate: 0.0 # by default, disable bias updates for grpo
    apply_rope_fusion: false
    
    optimizer:
      optimizer: "adam"
      lr: 5.0e-6
      min_lr: 4.9999e-6
      weight_decay: 0.1
      bf16: true
      fp16: false
      params_dtype: "float32"

      #adam
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1e-5

      #sgd
      sgd_momentum: 0.9

      #distributed optimizer
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true

      clip_grad: ${policy.max_grad_norm}

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "constant"
      lr_decay_iters: null
      lr_warmup_iters: 50
      lr_warmup_init: 4.9999e-6

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      data_parallel_sharding_strategy: "optim_grads_params"

data:
  add_generation_prompt: false
  max_input_seq_length: 1024
  dataset_name: squad
  add_bos: true
  add_eos: true
logger:
  log_dir: logs/sft-dsv3-megatron
  wandb_enabled: true
  tensorboard_enabled: false
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: sft-dev-yifu
    name: sft-dsv3-megatron
  tensorboard:
    log_dir: tb_logs-sft-dev-squad
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
cluster:
  gpus_per_node: 8
  num_nodes: 64
